#theme: jekyll-theme-minimal
title: Our GitHub home page
description: Blogs and Repos
#Github: https://github.com/codealba
logo: /images/unamed.jpg
#show_downloads: true
permalink: /blog/:year/:month/:day/:title
